// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.DbConnection;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240902231023_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.JwtRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("jwtRefreshTokens");
                });

            modelBuilder.Entity("UserService.Models.ServiceLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("serviceLogin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b27bcc3a-8ac1-4e59-a9e6-ab1c86bec745"),
                            Password = "a25980c153c7dc3c19c130498f40386e4c7675d6306efe9cdd8845f1b33f0d73",
                            Username = "devService"
                        });
                });

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Followers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowersNumber")
                        .HasColumnType("int");

                    b.Property<string>("Following")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3e37998-8cbf-4162-ba83-b7f28758b033"),
                            Address = "Str Test",
                            Country = "USA",
                            Currency = "USD",
                            Email = "bobeadorin@yahoo.com",
                            FirstName = "Joe",
                            Followers = "[]",
                            FollowersNumber = 0,
                            Following = "[]",
                            LastName = "Doe",
                            Likes = 0,
                            Password = "1f3085b93c4df1d85d28aa5d64efa559c0754bfd68dff0092a8eee16659f917c",
                            PhoneNumber = "0730733429",
                            Posts = "[]",
                            PostsNumber = 0,
                            Username = "JoeDoeTheFirst"
                        },
                        new
                        {
                            Id = new Guid("d2d49cf2-0ff4-4c6f-fd4d-08dcc7be62e6"),
                            Address = "Str.Ciuperceni",
                            Country = "USA",
                            Currency = "USD",
                            Email = "test@example.com",
                            FirstName = "Test",
                            Followers = "[]",
                            FollowersNumber = 0,
                            Following = "[]",
                            LastName = "Test",
                            Likes = 0,
                            Password = "8843be720a68ea1601d3e6e1ee12451572e516a120bf86c015573beca3c2d23e",
                            PhoneNumber = "0730733456",
                            Posts = "[]",
                            PostsNumber = 0,
                            Username = "TestUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
